/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Check the log or your email": {                 "en": "Check the log or your email",                     "de": "Log oder Emails prüfen",                          "ru": "Проверьте ваш почтовый ящик или логи ioBroker",   "pt": "Verifique o log ou o seu email",                  "nl": "Controleer het logboek of uw e-mail",             "fr": "Vérifiez le journal ou votre email",              "it": "Controlla il registro o la tua email",            "es": "Verifique el registro o su correo electrónico",   "pl": "Sprawdź dziennik lub swój e-mail",                "zh-cn": "查看日志或电子邮件"},
    "Connection settings": {                         "en": "Connection settings",                             "de": "Verbindungseinstellungen",                        "ru": "Настройки соединения",                            "pt": "Configurações de conexão",                        "nl": "Verbindingsinstellingen",                         "fr": "Paramètres de connexion",                         "it": "Impostazioni di connessione",                     "es": "Configuración de conexión",                       "pl": "Ustawienia połączenia",                           "zh-cn": "连接设置"},
    "Default settings": {                            "en": "Default settings",                                "de": "Standardeinstellungen",                           "ru": "Настройки по умолчанию",                          "pt": "Configurações padrão",                            "nl": "Standaard instellingen",                          "fr": "Paramètres par défaut",                           "it": "Impostazioni predefinite",                        "es": "Configuración por defecto",                       "pl": "Ustawienia domyślne",                             "zh-cn": "默认设置"},
    "Defaults": {                                    "en": "Defaults",                                        "de": "Voreinstellung",                                  "ru": "Значения по умолчанию",                           "pt": "Padrões",                                         "nl": "defaults",                                        "fr": "Par défaut",                                      "it": "Defaults",                                        "es": "Valores predeterminados",                         "pl": "Domyślne",                                        "zh-cn": "默认"},
    "E-mail adapter settings": {                     "en": "E-mail adapter settings",                         "de": "E-mail Adapter Einstellungen",                    "ru": "Настройки драйвера E-mail",                       "pt": "Configurações do adaptador de e-mail",            "nl": "Instellingen voor e-mailadapters",                "fr": "Paramètres de l'adaptateur de messagerie",        "it": "Impostazioni dell'adattatore di posta elettronica", "es": "Configuración del adaptador de correo electrónico", "pl": "Ustawienia adaptera poczty e-mail",               "zh-cn": "电子邮件适配器设置"},
    "Enable first the adapter to test email.": {     "en": "Enable first the adapter to test email.",         "de": "Adapter aktivieren, um Test-Email versenden zu können.", "ru": "Что бы протестировать драйвер, его надо сначало активировать.", "pt": "Ative primeiro o adaptador para testar o e-mail.", "nl": "Schakel eerst de adapter in om e-mail te testen.", "fr": "Activez d'abord l'adaptateur pour tester le courrier électronique.", "it": "Abilitare prima l'adattatore per testare la posta elettronica.", "es": "Primero habilite el adaptador para probar el correo electrónico.", "pl": "Najpierw włącz adapter, aby przetestować pocztę e-mail.", "zh-cn": "首先启用适配器来测试电子邮件。"},
    "Error: ": {                                     "en": "Error ",                                          "de": "Fehler ",                                         "ru": "Ошибка ",                                         "pt": "Erro",                                            "nl": "Fout",                                            "fr": "Erreur",                                          "it": "Errore",                                          "es": "Error",                                           "pl": "Błąd",                                            "zh-cn": "错误"},
    "From:": {                                       "en": "From",                                            "de": "Von",                                             "ru": "От",                                              "pt": "A partir de",                                     "nl": "Van",                                             "fr": "De",                                              "it": "A partire dal",                                   "es": "De",                                              "pl": "Od",                                              "zh-cn": "从"},
    "Host:": {                                       "en": "Host",                                            "de": "Host",                                            "ru": "Хост",                                            "pt": "Hospedeiro",                                      "nl": "gastheer",                                        "fr": "Hôte",                                            "it": "Ospite",                                          "es": "Anfitrión",                                       "pl": "Gospodarz",                                       "zh-cn": "主办"},
    "Is secure connection": {                        "en": "Is secure connection",                            "de": "Verschlüsselte Verbindung",                       "ru": "SSL соединение",                                  "pt": "É a conexão segura",                              "nl": "Is beveiligde verbinding",                        "fr": "Est une connexion sécurisée",                     "it": "È una connessione sicura",                        "es": "Es una conexión segura",                          "pl": "Czy bezpieczne połączenie",                       "zh-cn": "安全连接"},
    "Password:": {                                   "en": "Password",                                        "de": "Kennwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Port:": {                                       "en": "Port",                                            "de": "Port",                                            "ru": "Порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "SSL connection:": {                             "en": "SSL connection",                                  "de": "SSL Verbindung",                                  "ru": "SSL соединиение",                                 "pt": "Conexão SSL",                                     "nl": "SSL-verbinding",                                  "fr": "Connexion SSL",                                   "it": "Connessione SSL",                                 "es": "Conexión SSL",                                    "pl": "Połączenie SSL",                                  "zh-cn": "SSL连接"},
    "Service:": {                                    "en": "Service",                                         "de": "Service",                                         "ru": "Сервис",                                          "pt": "Serviço",                                         "nl": "Service",                                         "fr": "Un service",                                      "it": "Servizio",                                        "es": "Servicio",                                        "pl": "Usługa",                                          "zh-cn": "服务"},
    "Subject:": {                                    "en": "Subject",                                         "de": "Thema",                                           "ru": "Тема",                                            "pt": "Sujeito",                                         "nl": "Onderwerpen",                                     "fr": "Assujettir",                                      "it": "Soggetto",                                        "es": "Tema",                                            "pl": "Przedmiot",                                       "zh-cn": "学科"},
    "Test": {                                        "en": "Test",                                            "de": "Test",                                            "ru": "Тест",                                            "pt": "Teste",                                           "nl": "Test",                                            "fr": "Tester",                                          "it": "Test",                                            "es": "Prueba",                                          "pl": "Test",                                            "zh-cn": "测试"},
    "This is test email!": {                         "en": "This is test email!",                             "de": "Das ist eine Test-Email!",                        "ru": "Тестовое письмо",                                 "pt": "Este é um e-mail de teste!",                      "nl": "Dit is testmail!",                                "fr": "C'est un email de test!",                         "it": "Questa è la mail di prova!",                      "es": "Este es el correo electrónico de prueba!",        "pl": "To jest e-mail testowy!",                         "zh-cn": "这是测试邮件！"},
    "To:": {                                         "en": "To",                                              "de": "Nach",                                            "ru": "Кому",                                            "pt": "Para",                                            "nl": "Naar",                                            "fr": "À",                                               "it": "A",                                               "es": "A",                                               "pl": "Do",                                              "zh-cn": "至"},
    "Transport:": {                                  "en": "Transport",                                       "de": "Transport",                                       "ru": "Протокол",                                        "pt": "Transporte",                                      "nl": "Vervoer",                                         "fr": "Transport",                                       "it": "Trasporto",                                       "es": "Transporte",                                      "pl": "Transport",                                       "zh-cn": "运输"},
    "User defined": {                                "en": "User defined",                                    "de": "Benutzerdefiniert",                               "ru": "Пользовательские",                                "pt": "Usuário definido",                                "nl": "Gebruiker gedefinieerde",                         "fr": "Défini par l'utilisateur",                        "it": "Definito dall'utente",                            "es": "Usuario definido",                                "pl": "Określony przez użytkownika",                     "zh-cn": "用户自定义"},
    "User:": {                                       "en": "User",                                            "de": "Benutzer",                                        "ru": "Пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
};